name: CI/CD for webapp

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  deploy:
    name: Deploy web Application
    runs-on: amzn2-ami-kernel-5.10-hvm-2.0.20250108.0-x86_64-gp2
    steps:
      # Déployer sur EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Mettre à jour les paquets
            sudo yum update -y 
            
            # Installer nginx et git
            sudo yum install -y nginx git
            
            # Activer le service nginx
            sudo systemctl enable nginx
            
            # Démarrer le service nginx
            sudo systemctl start nginx
            
            # Cloner le dépôt
            cd /tmp/ && git clone https://github.com/thedovekana/github-actions-project.git  
            
            # Supprimer les fichiers par défaut de nginx et copier le code
             sudo rm -rf /usr/share/nginx/html/* && cp -r /tmp/github-actions-project/*  /usr/share/nginx/html/
             
            # Redémarrer nginx
            sudo systemctl restart nginx
